name: Test and Build - Spring Cloud Extension

on: [ push, pull_request ]

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - java-version: 8
            sonar: false
          - java-version: 11
            sonar: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache .m2
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository

          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Maven operation with Sonar
        if: ${{ matrix.sonar }} == 'false'
        run: |
          mvn -B -U -Pcoverage clean verify sonar:sonar -Dsonar.projectKey=AxonFramework_extension-springcloud -Dsonar.organization=axonframework -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven operation without Sonar
        if: ${{ matrix.sonar }} == 'true'
        run: |
          mvn -B -U clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify success to Slack
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: AGSEC92A
          status: SUCCESS
          color: good

      - name: Notify failure to Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: AGSEC92A
          status: FAILED
          color: danger
